config/routes.rb
Rails.application.routes.draw do
  root to: "stores#index" 

  resources :products

  resources :stores

  get  :download, to: "stores#download", defaults: { format: :xlsx }

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :store_products
  has_many :stores, through: :store_products

  validates_presence_of :code,
                        :name,
                        :weight,
                        :size,
                        :color,
                        :price
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :store_products
  has_many :products, through: :store_products

  validates_presence_of  :name,
                         :address,    
                         :city
end

app/models/store_product.rb
class StoreProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :store
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :error
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @store = Store.where(id: params[:id])    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:store_id, :code, :name, :weight, :size, :color, :price, :balance)
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all.order(name: :asc)
  end

  def download    
    unless params[:stores]
      flash[:error] = 'Выберите магазин(ы)'
      redirect_to root_path
      return
    end    
    if params[:stores]
      @stores = Store.where(id: params[:stores])
    end
    respond_to do |format|
      format.xlsx {render xlsx: 'download', filename: "store_products.xlsx"}
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.where(id: params[:id]).first
    @products = @store.products.order(name: :asc)    
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :metro_station, :city)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/application/_flash_messages.html.erb
<% flash.select{|t,m| m.present?}.each do |type, message| %>
  <% (message.kind_of?(Array) ? message : [message]).each do |m| %>
    <div class="error text-center margin-bottom margin-top"><%= m %></div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: "application/flash_messages", flash: flash %>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :store_id %><br>
    <%= f.number_field :store_id %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :balance %><br>
    <%= f.number_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Code</th>
      <th>Name</th>
      <th>Weight</th>
      <th>Size</th>
      <th>Color</th>
      <th>Price</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.store_id %></td>
        <td><%= product.code %></td>
        <td><%= product.name %></td>
        <td><%= product.weight %></td>
        <td><%= product.size %></td>
        <td><%= product.color %></td>
        <td><%= product.price %></td>
        <td><%= product.balance %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @product.store_id %>
</p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @product.weight %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @product.balance %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :metro_station %><br>
    <%= f.text_field :metro_station %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
  <div class="container">
    <h1 class="text-center margin-bottom margin-top">Stores of products</h1>
    <form action=<%= download_path%> method="GET">
      <table class="table">
        <thead class="thead">
          <tr>
            <th>
              <p class="header-checkbox"><input type="checkbox" class="form-check-input" id="all"></p>
            </th>
            <th>Store</th>
            <th>City</th>
            <th>Address</th>
            <th>Metro Station</th>
          </tr>
        </thead>
        <tbody class="tbody">
          <% @stores.each do |store| %>
              <tr class="tr" data-link="<%= store_path(store.id)%>">
                <td>
                  <div class="form-check parent-checkbox">
                    <label class="form-check-label checkbox">
                      <input type="checkbox" class="form-check-input checked" name="stores[]" value="<%= store.id %>">
                    </label>
                  </div>
                </td>
                <td class="click_link"><%= store.name %></td>
                <td class="click_link"><%= store.city %></td>
                <td class="click_link"><%= store.address %></td>
                <td class="click_link"><%= store.metro_station %></td>
              <tr>
          <% end %>
        </tbody>
      </table>
      <h1 class="text-center margin-bottom margin-top">Export products</h1>
      <div class="center">
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='product_name'>
              Название продукта
            </label>
          </div>
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='product_color'>
              Цвет
            </label>
          </div>
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='product_weight'>
              Вес
            </label>
          </div>
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='size'>
              Размер
            </label>
          </div>
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='product_price'>
              Цена
            </label>
          </div>
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='store_address'>
              Адрес магазина
            </label>
          </div>
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='metro_station'>
              Станция метро
            </label>
          </div>
          <div class="form-check inline">
            <label class="form-check-label">
              <input type="checkbox" class="form-check-input" name='fields[]' value='store_city'>
              Город
            </label>
          </div>
      </div>
      <div class="text-center margin-top">
        <%= content_tag(:button, "Export xlsx", :type=>:submit, class: 'btn btn-primary margin-top link')%>
      </div>
    </form>
  </div>

<script>
  $("#all").click(function() {
    $(".checked").prop('checked',$(this).prop('checked'));
  })
  $("td.click_link").click(function() { window.location = $(this).parent().data("link") })
</script>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<!doctype html>
<html lang="en">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DiplomasForContributors</title>
  </head>
  <body>
    <div class="container">
      <h1 class="text-center margin-bottom margin-top">Products of Stores</h1>
      <h3 class="text-center margin-bottom">Store: <%= @store.name %>, <%= @store.city %>, <%= @store.address %>, <%= @store.metro_station %></h2>

      <table class="table">
        <thead>
          <tr>      
            <th>Code</th>
            <th>Name</th>
            <th>Weight</th>
            <th>Size</th>
            <th>Color</th>
            <th>Price</th>
            <th>Balance</th>      
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>        
              <td><%= product.code %></td>
              <td><%= product.name %></td>
              <td><%= product.weight %></td>
              <td><%= product.size %></td>
              <td><%= product.color %></td>
              <td><%= product.price %></td>
              <td><%= StoreProduct.where(store_id: @store.id, product_id: product.id).first.balance %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-center margin-top">
        <%= link_to 'Back', stores_path, class: "btn btn-primary link" %>
      </div>
    </div>
  </body>
</html>